services:
  frontend:
    build: ./frontend
    command: npm run dev -- --host
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "4000:4000"
      - "4001:4001"
    env_file:
      - ./backend/src/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
      - db_data:/app/database

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  db_data:
    driver: local
