services:
  frontend:
    build: ./frontend
    command: npm run dev -- --host
    ports:
      - "3000:3000"
    # volumes:
    #   - ./frontend:/app
    #   - frontend_node_modules:/app/node_modules
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "4000:4000"
      - "4001:4001"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
      - db_data:/app/database
      - uploads_data:/app/uploads  # Add this line

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - uploads_data:/var/www/uploads  # Add this line
    depends_on:
      - frontend
      - backend

volumes:
  db_data:
    driver: local
  uploads_data:  # Add this volume
    driver: local