services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    # volumes: # changes to the frontend code will be reflected in the container/ live code updates
      # - ./frontend/src:/app/src
      # - ./frontend/package.json:/app/package.json
      # - ./frontend/package-lock.json:/app/package-lock.json

