services:
  frontend:
    build: ./frontend
    command: npm run dev -- --host
    ports:
      - "3000:3000"
    # volumes:
    #   - ./frontend:/app
    #   - frontend_node_modules:/app/node_modules
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/src/.env
    volumes:
      - db_data:/app/database

  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - frontend
  #     - backend

volumes:
  db_data:
    driver: local