services:
  frontend:
    build: ./frontend
    command: npm run dev -- --host
    ports:
      - "3000:3000"
    #volumes:
     # - ./frontend:/app
     # - /app/node_modules
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "4000:4000"
    # env_file:
    #   - ./backend/src/.env
    #volumes:
      #- db_data:/app/database

volumes:
  db_data:
    driver: local