services:
  frontend:
    build: ./frontend
    command: npm run dev -- --host
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # <- isso mantém os node_modules do container
    depends_on:
      - backend
    
  backend:  # <--- renomeado de mock-backend para backend
    build: ./backend
    #command: node mock-ws-server.js  # <--- se necessário
    ports:
      - "4000:4000"
    volumes:
    - ./backend/database:/app/database
  
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
  
  # backend:
  #   build: ./backend
  #   container_name: backend
  #   ports:
  #     - "4000:4000"
  #   # env_file:
  #   #   - ./backend/src/.env
  #   volumes:
  #     - db_data:/app/database

volumes:
  db_data:
    driver: local



    