// game constants for multiplayer Pong

const VIRTUAL_WIDTH = 1456;
const VIRTUAL_HEIGHT = 816;
const VIRTUAL_BORDER_TOP = 110;
const VIRTUAL_BORDER_BOTTOM = 130;
const VIRTUAL_BORDER_X = 120;

const GAME_AREA_HEIGHT = VIRTUAL_HEIGHT - VIRTUAL_BORDER_TOP - VIRTUAL_BORDER_BOTTOM;
const GAME_AREA_WIDTH = VIRTUAL_WIDTH - (VIRTUAL_BORDER_X * 2);

const BALL_SPEED_MIN = VIRTUAL_WIDTH / 8;
const BALL_SPEED_MAX = VIRTUAL_WIDTH / 2;
const BALL_SIZE = VIRTUAL_HEIGHT * 0.025;

const PADDLE_SPEED = VIRTUAL_HEIGHT / 4;
const PADDLE_HEIGHT = GAME_AREA_HEIGHT * 0.15;
const PADDLE_WIDTH = VIRTUAL_WIDTH * 0.01;
const PADDLE_MARGIN_X = 0.20;

const LEFT_PADDLE_X = VIRTUAL_WIDTH * PADDLE_MARGIN_X;
const RIGHT_PADDLE_X = VIRTUAL_WIDTH * (1 - PADDLE_MARGIN_X) - PADDLE_WIDTH;

const SCORE_MAX = 2;
const GAME_FPS = 60;

module.exports = {
	VIRTUAL_WIDTH,
	VIRTUAL_HEIGHT,
	VIRTUAL_BORDER_TOP,
	VIRTUAL_BORDER_BOTTOM,
	VIRTUAL_BORDER_X,
	GAME_AREA_HEIGHT,
	GAME_AREA_WIDTH,

	BALL_SPEED_MIN,
	BALL_SPEED_MAX,
	BALL_SIZE,

	PADDLE_SPEED,
	PADDLE_HEIGHT,
	PADDLE_WIDTH,
	PADDLE_MARGIN_X,
	LEFT_PADDLE_X,
	RIGHT_PADDLE_X,

	SCORE_MAX,
	GAME_FPS
}; 