module.exports = {
  ACCESS_TOKEN_REQUIRED: 'ACCESS_TOKEN_REQUIRED', // "Access token required"
  INVALID_OR_EXPIRED_TOKEN: 'INVALID_OR_EXPIRED_TOKEN', // "Invalid or expired token"
  USER_NOT_FOUND: 'USER_NOT_FOUND', // "User not found"
  USER_NO_LONGER_EXISTS: 'USER_NO_LONGER_EXISTS', // "User no longer exists"
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR', // "Internal server error"
  EMAIL_REQUIRED: 'EMAIL_REQUIRED', // "Email is required"
  EMAIL_AND_PASSWORD_REQUIRED: 'EMAIL_AND_PASSWORD_REQUIRED', // "Email and password are required"
  INVALID_EMAIL_FORMAT: 'INVALID_EMAIL_FORMAT', // "Invalid email format"
  PASSWORD_TOO_SHORT: 'PASSWORD_TOO_SHORT', // "Password must be longer than 6 characters"
  ERROR_HASHING_PASSWORD: 'ERROR_HASHING_PASSWORD', // "Error hashing password"
  USER_EXISTS: 'USER_EXISTS', // "Email or username already exists"
  ERROR_SAVING_USER: 'ERROR_SAVING_USER', // "Error saving user to database"
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS', // "Invalid email or password"
  ERROR_VERIFYING_PASSWORD: 'ERROR_VERIFYING_PASSWORD', // "Error verifying password"
  AUTHENTICATOR_TOKEN_REQUIRED: 'AUTHENTICATOR_TOKEN_REQUIRED', // "Authenticator token is required"
  INVALID_AUTHENTICATOR_TOKEN: 'INVALID_AUTHENTICATOR_TOKEN', // "Invalid authenticator token"
  ERROR_CREATING_SESSION: 'ERROR_CREATING_SESSION', // "Error creating session"
  ERROR_FETCHING_USER: 'ERROR_FETCHING_USER', // "Error fetching user from database"
  ERROR_GENERATING_QR: 'ERROR_GENERATING_QR', // "Error generating QR code"
  ERROR_SAVING_SECRET: 'ERROR_SAVING_SECRET', // "Error saving secret to database"
  INVALID_TOKEN: 'INVALID_TOKEN', // "Invalid token"
  USER_NOT_FOUND_OR_2FA: 'USER_NOT_FOUND_OR_2FA', // "User not found or authenticator not activated"
  ERROR_FETCHING_SECRET: 'ERROR_FETCHING_SECRET', // "Error fetching secret from database"
  INVALID_NEW_USERNAME: 'INVALID_NEW_USERNAME', // "Invalid new username."
  USERNAME_EXISTS: 'USERNAME_EXISTS', // "Username already exists."
  DATABASE_ERROR: 'DATABASE_ERROR', // "Database error."
  INVALID_NEW_PASSWORD: 'INVALID_NEW_PASSWORD', // "Invalid new password."
  ERROR_HASHING_NEW_PASSWORD: 'ERROR_HASHING_NEW_PASSWORD', // "Error hashing password."
  AUTHORIZATION_CODE_EXPIRED: 'AUTHORIZATION_CODE_EXPIRED', // "Authorization code expired or invalid. Please try logging in again."
  AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED', // "Authentication failed. Please try again."
  ERROR_FETCHING_USERS: 'ERROR_FETCHING_USERS', // "Error fetching users from database"

  // CHECK - doesnt need to send anything to FE? meaning: not visible in terms of UI
  ERROR_DELETING_REFRESH_TOKEN: 'ERROR_DELETING_REFRESH_TOKEN', // "Error deleting refresh token"
  ERROR_LOGGING_OUT_ALL: 'ERROR_LOGGING_OUT_ALL', // "Error logging out from all devices"
  ERROR_SAVING_REFRESH_TOKEN: 'ERROR_SAVING_REFRESH_TOKEN', // "Error saving refresh token"

  // SUCESS MESSAGES
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS', // "Logout successful"
  LOGOUT_ALL_SUCCESS: 'LOGOUT_ALL_SUCCESS', // "Logged out from all devices"
};
